### ISSUE TITLE
Disable change of upper bound of version ranges of dependencies in MANIFEST.MF

### ISSUE THREAD

**Issue by hegewald** [inventage/version-tiger#16]
Actual the plugin changes version ranges of dependencies inside MANIFEST.MF.

Example:
Version of com.example.plugin will be change from 2.0.16 to 2.0.17
If there is an other plugin with a dependency to com.example.plugin the MANIFEST now will be changed like this

before: com.example.plugin;bundle-version="[2.0.16,2.1.0)"
after: com.example.plugin;bundle-version="[2.0.17,3.0.0)"

In my opinion the change of the lower bound is ok, but the change of the upper bound should not performed.

**Comment by b8** [comment]
Finally, I've a fix for this. I've introduced the following modes:

- *adaptive* (default): Detects if the range currently allows major, minor or bugfix changes and adapts the range accordingly.
- *Bugfix*: Sets the upper bound to the next bugfix version (exclusive) and sets the lower bound to the new version (inclusive).
- *Major*: Sets the upper bound to the next major version (exclusive) and sets the lower bound to the new version (inclusive).
- *Minor*: Sets the upper bound to the next minor version (exclusive) and sets the lower bound to the new version (inclusive).
- *NoChange*: Does not change the version range.
Strict: Sets the lower and upper bound to the new version (inclusive qualifiers).
- *UpperToBugfix*: Sets the upper bound to the next bugfix version (exclusive) and leaves the lower bound as it is.
- *UpperToMajor*: Sets the upper bound to the next major version (exclusive) and leaves the lower bound as it is.
- *UpperToMinor*: Sets the upper bound to the next minor version (exclusive) and leaves the lower bound as it is.

The setting can be done in the preferences page (ui) or as command: ``setting dependency.range.change minor``
