### ISSUE TITLE
CLI updateReferences -> "Can't update references in manifest: ... null"

### ISSUE THREAD

**Issue by drsgoodall** [inventage/version-tiger#32]
Following on from case #29 I have pulled the current git repo (last commit is 6de166d77208e1f8f738ef445eef91b59073a917).

Attempting to updateReferences now results in this error message when trying to update the reference.

ERROR - com.example.reference.project - REFERENCE FROM com.example.current.project- Can't update references in manifest: /path/to/project/com.example.current.project/META-INF/MANIFEST.MF. null

This appears to be due to the similar issue in #29 where the oldVersion is not defined, thus old version number checks do not pass. As a quick hack on my side I change the first if in VersionRange#updateVersionIfOldMatches to ;
                if (oldVersion == null || rangeMatches(oldVersion)) {
from
                if (rangeMatches(oldVersion)) {

and this appears to make this feature work for me. However I am not sure if this has any unintended side-effects.

**Comment by b8** [comment]
Thanks for the bugfix!
