### ISSUE TITLE
OSGI versions are not updated

### ISSUE THREAD

**Issue by DzianisFrydliand** [inventage/version-tiger#38]
I'm using the latest version of plugin (1.3.1) and Eclipse 4.4.2

After trying to update versions in my workspace I get only poms updated. No changes in plugin.xml, feature.xml, *.product, MANIFEST.MF at all. Have to update those versions manually.

The previous version worked fine for me.

How can I debug the issue to find a root of the problem? I guess it can be some misconfiguration...

**Comment by b8** [comment]
Hmm, check...
* if your artifact types have the correct packaging: eclipse-plugin, eclipse-repository, etc...
* if the versions between pom and manifest are in sync initially

Starting from the exact same workspace, does versiontiger 1.2.0 work and versiontiger 1.3.1 does not?

**Comment by DzianisFrydliand** [comment]
I'm sure that packaging is correct because my projects are assembled with maven+tycho and I have no problems with that.

**Comment by OLibutzki** [comment]
I second this. com.inventage.tools.versiontiger.internal.impl.ReferencesUpdater.setVersion(MavenVersion) checks for isVersionInherited() and skips the setVersion Call. This causes the artifacts (features, products,...) not to be updated.

**Comment by OLibutzki** [comment]
I fixed it and created a pull request

**Comment by b8** [comment]
Hmm, seems really to be a bug. Actually, any version request for childs (which inherit version) does not make sense. But when versioning the parent, all references for all children should be updated. This seems to be missing or I don't find the code now.

**Comment by b8** [comment]
The bug is now fixed but with another solution. But thanks a lot for your investigation!
