### ISSUE TITLE
Maven plugin

### ISSUE THREAD

**Issue by OLibutzki** [inventage/version-tiger#39]
Hi,

in my opinion it would be great to use version-tiger as a Maven plugin. Are there any plans to provide this?

Kind regards
Oliver

**Comment by b8** [comment]
Great idea, will be available in the next version. It's just a simple mojo to execute batch files.

**Comment by b8** [comment]
Usage: ``mvn versiontiger:execute -DstatementsFile=release.versiontiger``
(or fully qualified ``mvn com.inventage.tools.versiontiger:versiontiger-maven-plugin:execute -DstatementsFile=release.versiontiger``)
