### ISSUE TITLE
Installation not working for Eclipse Mars (1.2.x)

### ISSUE THREAD

**Issue by ghost** [inventage/version-tiger#51]
We use version tiger 1.2.x because since 1.3.x we get an validation error in jenkins 
( [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.18.0:validate-version (default-validate-version) on project com.xxx.build.eclipse.common: OSGi version 1.9.9.qualifier in META-INF/MANIFEST.MF does not match Maven version 1.9.9 in pom.xml -> [Help 1])

Unfortunately, version 1.2.x is not installable:
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=_home_xxx_.eclipse_oomph_ide-kepler_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
The file "/home/xxx/.eclipse/oomph/.p2/pool/features/com.inventage.tools.versiontiger.gui_1.2.0.RELEASE" does not exist

**Comment by b8** [comment]
I'll have to look at why 1.2 is not installable...

For the 1.3.x releases: I think  you're missing the `osgi.release.qualifier` setting. By default, tycho doesn't like a qualifier in release versions, so `osgi.release.qualifier` has to be set to an empty string (I guess this is the default). You can also set this in the workspace preferences when using the eclipse plug-in.

The other solution is to tell tycho that it should not be strict about version incompatibilities (e.g. in release versions), e.g.:
```xml
<profile>
    <id>release</id>
    <!-- versions of MANIFEST.MF and pom.xml don't have to match! -->
    <build>
        <plugins>
            <plugin> 
                <groupId>org.eclipse.tycho</groupId> 
                <artifactId>tycho-packaging-plugin</artifactId> 
                <version>${tycho.version}</version> 
                <configuration> 
                    <strictVersions>false</strictVersions>                                                  
                </configuration> 
            </plugin>
        </plugins>
    </build>
</profile>
```
